import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import antonpc from "../public/antonpc.webp";
import code from "../public/code.png";
import customSolutions from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import bose from "../public/bose_landing.jpg";
import mybike from "../public/mybike_landing.jpg"
import parcelapp from "../public/parcel-request-app_vue.jpg"
import todoapp from "../public/todo-app_react.jpg"

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyanton</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl "
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  target='_blank'
                  rel="noreferrer"
                  href="https://drive.google.com/file/d/1iPzayp3gGzcUUfSYqjd9k7i9iGitvOlw/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Anton Tarovyk
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Frontend Developer.
            </h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto'>
              I&apos;m 19yo Frontend developer working with React, Redux,
              RestAPI used with TypeScript.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400 ">
              <a
                href='https://www.linkedin.com/in/anton-tarovyk-a38b42242/'
                target='_blank'
                rel="noreferrer"
                className='hover:text-gray-200 transition duration-200 ease-in-out'
              >
                <AiFillLinkedin />
              </a>
              <a
                href='https://github.com/purpleFade'
                target='_blank'
                rel="noreferrer"
                className='hover:text-gray-200 transition duration-200 ease-in-out'
              >
                <AiFillGithub />
              </a>
            </div>
            <div className="flex items-center justify-center h-screen">
              <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
                <Image src={antonpc} layout="fill" objectFit="cover" alt='Anton is working'/>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Create custom web applications for businesses or individuals,
              leveraging your expertise in frontend development to build
              <span className='text-teal-500'>responsive</span> and{' '}
              <span className='text-teal-500'>efficient</span> user interfaces.
              Create and launch your own apps or tools that utilize React,
              TypeScript, Redux, and REST APIs. It could be anything from
              productivity tools to niche applications that solve{' '}
              <span className='text-teal-500'>specific</span> problems.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={customSolutions} width={100} height={100} alt='custom solutions'/>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Custom Solutions
              </h3>
              <p className="py-2">
                {' '}
                Offer tailored solutions to businesses that require specific
                functionalities or customizations in their applications,
                utilizing your expertise in frontend technologies.
              </p>
              <h4 className="py-4 text-teal-600">Technologies I use</h4>
              <p className='text-gray-800 py-1'>TypeScript</p>
              <p className='text-gray-800 py-1'>ReactJS</p>
              <p className='text-gray-800 py-1'>Redux</p>
              <p className='text-gray-800 py-1'>RestAPI</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt='code'/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&apos;s make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Coding Tools I Use</h4>
              <p className="text-gray-800 py-1">VS Code</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt='consulting'/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">Work in team</h3>
              <p className="py-2">
                Collaboration fuels innovation.
                Let&apos;s join forces and amplify your project&apos;s potential through combined expertise and teamwork.
              </p>
              <h4 className="py-4 text-teal-600">Contact me</h4>
              <p className="text-gray-800 py-1 ">
                <a
                  target='_blank'
                  rel='noreferrer'
                  href='mailto:tarovykanton@gmail.com'
                  className=' hover:text-teal-400 transition duration-200 ease-in-out'
                >
                  Email
                </a>
              </p>
              <p className="text-gray-800 py-1">
                <a
                  target='_blank'
                  rel='noreferrer'
                  href='https://www.linkedin.com/in/anton-tarovyk-a38b42242/'
                  className=' hover:text-teal-400 transition duration-200 ease-in-out'
                >
                  Linkedin
                </a>
              </p>
              <p className="text-gray-800 py-1">
                <a
                  target='_blank'
                  rel='noreferrer'
                  href='t.me/@refuelingkid'
                  className=' hover:text-teal-400 transition duration-200 ease-in-out'
                >
                  Telegram
                </a>
              </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a frontend developer, I have done work for 
              <span className="text-teal-500"> agencies </span>
              and collaborated with talanted people to create digital products
              for consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer programming services.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a
                href='https://purplefade.github.io/react_todo-app-with-api/'
                target='_blank'
                rel='noreferrer'
              >
                <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={todoapp}
                alt='Todo app React'
                />
              </a>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                 Todo app is built using React and TypeScript offering a user-friendly platform for managing tasks.🔥️
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href='https://github.com/purpleFade/Parcel-Delivery-Request-App'
                target='_blank'
                rel='noreferrer'
              >
                <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={parcelapp}
                alt='Parcel delivery request app'
                />
              </a>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Parcel delivery request app is built using Vue.js, CSS, HTML, and TypeScript offering a user-friendly platform for parcel delivery.🔥️
              </p>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href='https://purplefade.github.io/layout_landing-page/'
                target='_blank'
                rel='noreferrer'
              >
                <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={mybike}
                alt='MyBiKE Landing Page'
                />
              </a>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                My Bike&apos;s website is built using JavaScript, SCSS, and HTML, offering a user-friendly platform for bike enthusiasts.🔥️
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href='https://purplefade.github.io/layout_miami/'
                target='_blank'
                rel='noreferrer'
              >
                <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={bose}
                alt='Bose Landing Page'
                />
              </a>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Bose&apos;s landing page showcases their products and brand using JavaScript, SCSS, and HTML for an engaging online experience.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
